spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lockdb
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: drop-and-create
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        